### PR TITLE
Bug: menu stack panel

### LINKED ISSUE #187: Menu commands not updating results on ItemStackPanel, need to select item to update
recipe-item & add-required-ingredients commands

### PR DESCRIPTION
**Pull request by yican95**
closes #187

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/menu/AddRequiredIngredientsCommand.java [hunk 1]
```diff
@@ -69,6 +72,8 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
         model.updateFilteredItemList(PREDICATE_SHOW_ALL_ITEMS);
         model.commitAddressBook();
 
+        EventsCenter.getInstance().post(new DisplayItemListRequestEvent());
+        EventsCenter.getInstance().post(new JumpToListRequestEvent(index));
```
Comment (AZhiKai) [inline src/main/java/seedu/address/logic/commands/menu/AddRequiredIngredientsCommand.java]: I get the event to display the item list, but I don't get the jump to list request. Could you give an example of how these two events is related to add the ingredients?

Comment (yican95) [reply src/main/java/seedu/address/logic/commands/menu/AddRequiredIngredientsCommand.java]: JumpToListRequest is for the stack panel.
Recipe and required ingredients are only displayed on the stack panel.

Comment (AZhiKai) [reply src/main/java/seedu/address/logic/commands/menu/AddRequiredIngredientsCommand.java]: Sounds good, thanks!
