### PR TITLE
v1.3: Set to default data rather than blank XML

### LINKED ISSUE #104: Unable to create account
**Describe the bug**
If the system has no existing account, no one is able to login at all, as only an admin can create account, supposedly he/she would need an account in the first place.

One remedy is to allow self-register, and assume that the owner will assign the rank accordingly (coming in v2.0). That means that as long as no rank is assigned, the user won't be able to execute any commands anyway.

Another solution is to have a default `root` account in the `addressbook.xml` with a default password, such that the admin can log in and change it on the spot. 

**To Reproduce**
1. Clear the `addressbook.xml`
2. You can't login because there's no existing account, and you can't create new accounts because you need to be logged in

### PR DESCRIPTION
**Pull request by AZhiKai**
This PR fixes #104.

When the `clear` command is executed, reset the xml to the default state with the root account. That is, everything else will be removed except for the root account so that the user will be able to login again to re-setup the system. The same logic also applies when the .xml is not found. This ensures that the system will be accessible in any state with the root account (id: root, password: 1122qq)

Please ignore the Persons that are still being populated as it's pending to be removed in future commits.

Still work in progress, left with test cases.

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -64,7 +65,7 @@ public ModelManager() {
 
     @Override
     public void resetData(ReadOnlyAddressBook newData) {
-        versionedAddressBook.resetData(newData);
+        versionedAddressBook.resetData(SampleDataUtil.getSampleAddressBook());
```
Comment (AZhiKai) [inline src/main/java/seedu/address/model/ModelManager.java]: To be reviewed again. Perhaps worth checking if `newData` is an empty `AddressBook` or not. If it's not, then we assume that somewhere, this method is called to reset the current `AddressBook` to another set of data which consist of existing accounts. Otherwise if it's an empty `AddressBook`, we populate it with only the root account.

Comment (AZhiKai) [reply src/main/java/seedu/address/model/ModelManager.java]: Populate with root account inside `Clear` command instead of here.

**Comment by AZhiKai** [comment]
Ready for review.
Ignore the coverage as I purposely commented out one test which might have caused the decrease. Will need to handle the test case when we come to fixing #129 or basically #21

**Comment by HyperionNKJ** [comment]
> This PR fixes #104.
> 
> When the `clear` command is executed, reset the xml to the default state with the root account. That is, everything else will be removed except for the root account so that the user will be able to login again to re-setup the system. The same logic also applies when the .xml is not found. This ensures that the system will be accessible in any state with the root account (id: root, password: 1122qq)
> 
> Please ignore the Persons that are still being populated as it's pending to be removed in future commits.
> 
> Still work in progress, left with test cases.

Looks good to me! 
I myself encountered this problem when trying to set up the project on my Desktop. Had to manually create the "data/addressbook.xml" file and add a working account in it to be able to execute commands. This PR will resolve this completely! 😄

**Comment by AZhiKai** [comment]
> ## Pull Request Test Coverage Report for [Build 478](https://coveralls.io/builds/19651672)
> * **3** of **3**   **(100.0%)**  changed or added relevant lines in **2** files are covered.
> * **2** unchanged lines in **1** file lost coverage.
> * Overall coverage decreased (**-0.02%**) to **88.87%**
> 
> Files with Coverage Reduction	New Missed Lines	%
> [src/main/java/seedu/address/logic/commands/menu/TodaySpecialCommand.java](https://coveralls.io/builds/19651672/source?filename=src%2Fmain%2Fjava%2Fseedu%2Faddress%2Flogic%2Fcommands%2Fmenu%2FTodaySpecialCommand.java#L48)	2	48.0%
> Totals	[Coverage Status](https://coveralls.io/builds/19651672)
> Change from base [Build 456](https://coveralls.io/builds/19637420):	-0.02%
> Covered Lines:	3601
> Relevant Lines:	4052
> ##### 💛 - [Coveralls](https://coveralls.io)

Hi @yican95  i suppose you'll improve the coverage on your side. Merging this PR for now.
