### PR TITLE
v1.4 mass delete & delete by name

### LINKED ISSUE #108: Enhance delete-item command
Provide option to mass delete items and delete by name

### LINKED ISSUE #241: [PE Dry Run]Unable to delete item with name parameter
screenshot 2018-11-02 at 4 49 01 pm

UG says I can delete item with the specified NAME.
I tried
delete-item hello

screenshot 2018-11-02 at 4 48 21 pm

Does not work. Only INDEX works. 
As per my other Issue submitted, allowing for multiple items of same name, different price, will delete-tem NAME delete all the items with the same name?

<hr>

**Reported by:** @ihwk1996
**Severity:** `Medium`

<sub>[original: nus-cs2103-AY1819S1/pe-dry-run#878]</sub>

### LINKED ISSUE #248: [PE Dry Run]inconsistent command suggestion
image

The command sample depicts "edits" while user guide depicts "add"

<hr>

**Reported by:** @crimsonang
**Severity:** Not Specified

<sub>[original: nus-cs2103-AY1819S1/pe-dry-run#1203]</sub>

### PR DESCRIPTION
**Pull request by yican95**
This closes #108, closes #241, closes #248.

### CODE REVIEW

File: src/main/java/seedu/restaurant/logic/parser/menu/ItemParserUtil.java [hunk 1]
```diff
@@ -52,4 +56,30 @@ public static double parsePercent(String percent) throws ParseException {
...
+        requireNonNull(indexOrName);
+        String trimmedIndexOrName = indexOrName.trim();
+
+        if (StringUtil.isNonZeroUnsignedInteger(trimmedIndexOrName)) {
+            return Index.fromOneBased(parseInt(trimmedIndexOrName));
+        }
+
+        // Need to check if index is zero if not it will parse "0" as Name
+        if ("0".equals(trimmedIndexOrName)) {
+            throw new ParseException(MESSAGE_NOT_INDEX_OR_NAME);
```
Comment (AZhiKai) [inline src/main/java/seedu/restaurant/logic/parser/menu/ItemParserUtil.java]: What if it's some other value other than `"0"`?

Comment (yican95) [reply src/main/java/seedu/restaurant/logic/parser/menu/ItemParserUtil.java]: If it is a positive value, it will parse as Index. If it is a negative value, it will throw a parse exception. It will not parse as Name due to Name only allow alphanumeric characters.

Comment (yican95) [reply src/main/java/seedu/restaurant/logic/parser/menu/ItemParserUtil.java]: But if the value is greater than the maximum unsigned integer value, it will be parse as Name.

Comment (AZhiKai) [reply src/main/java/seedu/restaurant/logic/parser/menu/ItemParserUtil.java]: I see, okay sounds great.

**Comment by yican95** [comment]
delete item also has #239. I think separating the delete-item command to delete-item-index and delete-item-name will solve that issue.

**Comment by yican95** [comment]
Closes #241, #248.
